apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard-svc
  namespace: kubernetes-dashboard
  labels:
    app: kubernetes-dashboard-svc
spec:
  ports:
  - port: 443
    targetPort: 8443
    nodePort: 30043
    name: dashboard-port
  selector:
    app: kubernetes-dashboard
  type: NodePort